### ISSUE TITLE
How to get a high frame rate picture

### ISSUE THREAD

**Issue by JinghangLi** [driving-behavior/DBNet#10]
After downloading and viewing your open source data set, I would like to ask you the following two questions:
1. When reading the paper, I saw that you use a camera frame rate of 30 frames per second, but download a data set frame rate of 1 frame per second. Will you provide higher frame rate image data?
2. Download data set found that a large part of the data for the cropped 66x200 resolution image, where can I download the original data set?
Thank you！

**Comment by wangjksjtu** [comment]
Hi Jinghang,

Thanks for your interest in this work. The original higher resolution image can be accessed from the raw data `dvr_1920x1080` folders. For the convenience, we will also add `dvr_1920x1080` for prepared data.

For higher frame rate image, we will upload the original video (30fps) as soon as possible, so you can downsample the videos by yourself or the scripts provided.

Thanks for the question. We will update the dataset asap:)

**Comment by JinghangLi** [comment]
Thank you very much for your answer.

May I ask when the dataset will be updated? Or can I contact you to get some videos of the specified clips? It's very important to the next stage of my work.

Thanks a lot :)

**Comment by wangjksjtu** [comment]
We will update the dataset in these two days. I will let you know when it is finished :)

**Comment by wangjksjtu** [comment]
Hi Jinghang,

Thanks for the patience! We have updated the dataset. Please feel free to contact us if you have any further questions :)

**Comment by JinghangLi** [comment]
Hi Wang

Thank you very much for your patience, help and timely reply to the message.
I'm downloading the video data set now, and I'll let you know if I have any questions later.
Thank you very much
