### ISSUE TITLE
Annotations besides behaviors

### ISSUE THREAD

**Issue by bigsheep2012** [driving-behavior/DBNet#11]
Hello DBNet team,
Thanks for releasing this dataset.

May I know if there are annotations in the dataset for object detection?
Like semantic label or bounding box for each point cloud frame.

Many thanks

**Comment by wangjksjtu** [comment]
Thanks for your interest! 

For now, we didn't annotate the labels for object detection or semantic/instance segmentation. And we don't have a plan to complement them in the short term. (however, we agree that these labels are beneficial and we believe DBNet will add them in the future) For these tasks, we suggest you to use KITTI, Cityscape or BDDV.
