### ISSUE TITLE
Question about DBNet/tools/las2fmap.py

### ISSUE THREAD

**Issue by YamasakiRuna** [driving-behavior/DBNet#14]
Hi, it's me again and here comes other two question in it.
1.
_line164> W_ij_XOY = 1.414 * GSD / (Z_ij)_
Which is to get the distance to the center of the cell(i,j), method from _Automated Extraction of Road Markings from Mobile Lidar Point Clouds_ 
![file1](https://user-images.githubusercontent.com/48087204/53717772-86dd9680-3e9c-11e9-8e3c-c18501638e6e.jpg)
but the method in it says that there should be D_kij instead of Z_ij in line 164. Z_ij is just the height of the point in cell(i,j), also we didn’t find the code for calculating D_kij in las2fmap.py.

2.
_line165> W_ij_H = H_ij * (h_min - z_min) / (z_max - h_max) / (Z_ij)_
In _Automated Extraction of Road Markings from Mobile Lidar Point Clouds_,
![file2](https://user-images.githubusercontent.com/48087204/53717797-9b219380-3e9c-11e9-8780-7a90657057e1.jpg)
,  there isn’t divided by (Z_ij).

Could you help me with them?
Thanks.

**Comment by wangjksjtu** [comment]
Hi, sorry for the delay... I was busy doing other projects so I had little time to response.

I checked the code today and found it is indeed a bug in the script. Thank you for pointing it out :)

I have fixed the bug and updated the repo. For your convenience, I also uploaded a `.las` point cloud file to the Google Drive (https://drive.google.com/file/d/1lxl7M2MTA7afg5UItA5hCvh-Wt5bTSNJ/view?usp=sharing). You can easily download it and test the script. Hope it helps :)

Thanks a lot!
JIngkang
