### ISSUE TITLE
Broken image in the data

### ISSUE THREAD

**Issue by YihaoX** [driving-behavior/DBNet#16]
Hi!
_66.jpg-119.jpg_ in _dbnet-2018\train\48\dvr_1920x1080_ of _ftp://user1:User1314@121.192.180.185/dataD/dbnet-2018.zip_ could not be load. Could you plz check that? Thanks a lot for that!

**Comment by YihaoX** [comment]
I download it again for checking and they are also could not be load.  
Do you mind just upload with 66.jpg-119.jpg in dbnet-2018\train\48\dvr_1920x1080 as a small patch because of the bad download speed from out of China?
Thanks!

**Comment by wangjksjtu** [comment]
Hi, sorry for the broken images. We will check and fix them as soon as possible.

**Comment by wangjksjtu** [comment]
Hi, the broken images have been fixed! Also, we will upload the prepared data to the google drive. I will let you know when it is finished :)

**Comment by YihaoX** [comment]
> Hi, the broken images have been fixed! Also, we will upload the prepared data to the google drive. I will let you know when it is finished :)

Thanks for that!<3

**Comment by wangjksjtu** [comment]
Hi, the prepared data have been uploaded to the google drive (https://drive.google.com/file/d/1WxzOrhvMnHCOkh6EFGWltflyPb_UnGqo/view?usp=sharing). Sorry for the delay :)
