### ISSUE TITLE
Error when using las2fmap.py

### ISSUE THREAD

**Issue by YamasakiRuna** [driving-behavior/DBNet#17]
Hi, thank for fixing the BUGs and it works great with _examples.las_.
But when I use the las file you prvides in _ftp://user1:User1314@121.192.180.185/dataD/dbnet-2018.zip_, which is the prepared data( I use _dbnet-2018\train\1\points_16384\0.las_ for test), it comes the error:

`Traceback (most recent call last):
  File "J:/DBNet-master/tools/las2fmap.py", line 290, in <module>
    main()
  File "J:/DBNet-master/tools/las2fmap.py", line 274, in main
    if get_fmap(p):
  File "J:/DBNet-master/tools/las2fmap.py", line 233, in get_fmap
    rotate_about_center(fmap, 180, 1.0))
  File "J:/DBNet-master/tools/las2fmap.py", line 98, in rotate_about_center
    return cv2.warpAffine(src, rot_mat, (int(math.ceil(nw)), int(math.ceil(nh))), flags=cv2.INTER_LANCZOS4)
cv2.error: OpenCV(3.4.4) C:\projects\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2611: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'
`
which means I could not make fmap by myself, could you please help me?

**Comment by wangjksjtu** [comment]
This is because down-sampled point clouds are not dense enough to be mapped into the 2D plane. In the paper, original point clouds which contain millions of points (like `example.las`) in each scene are used to generate feature maps directly to maintain enough information.

**Comment by YamasakiRuna** [comment]
Sorry for late reply! 
Got it! Thanks a lot!
By the way, would you like to share the code with using LSTM? I'm a noob of Tensorflow and want to learn how to do like your paper.

**Comment by wangjksjtu** [comment]
Thanks for the interest! For now, I have other projects to work on so maybe there is no time to add more models and results. There are also many fantastic tutorials of tensorflow (including LSTM ops) on Github, which are good materials to learn and start from :)

By the way, any pull-requests about new models/results are highly welcomed and appreciated!
