### ISSUE TITLE
Restore resnet152_pn's, Error: Key not found

### ISSUE THREAD

**Issue by Rocalman** [driving-behavior/DBNet#19]
Hi!  When I run the evaluate.py, 
python evaluate.py --model_path logs_Res_G/resnet152_pn/model.ckpt --test True
Try to restore the resnet152_pn's  model,but I get the error: 
NotFoundError (see above for traceback): Key conv1/bn/conv1/bn/moments/Squeeze_1/ExponentialMovingAverage not found in checkpoint

Thanks!

**Comment by CugAgo** [comment]
I encountered the same problem, how did you solve it？
