### ISSUE TITLE
http://www.drivingbehavior.org con not be connected

### ISSUE THREAD

**Issue by wtaodd** [driving-behavior/DBNet#2]

**Comment by wangjksjtu** [comment]
Sorry for the delay. Yeah, recently, the website has some problems and we are working on it. Thanks for your interests and attention, I will inform you as soon as it it fixed.

**Comment by wangjksjtu** [comment]
The new website http://www.dbehavior.net is available now. We are going to release the DBNet data and tasks. Stay tuned!
