### ISSUE TITLE
DNN-LSTM problem

### ISSUE THREAD

**Issue by jycccccccc** [driving-behavior/DBNet#24]
Thanks for the paper and your job.
I have a question about the DNN-LSTM structure. You said in the paper that you stacked LSTM design will capture the temporal information and outperform DNN-only setting. But what I see from the code is that you shuffle the data in the provider file, which means the temporal information is lost. Also I didn't see you feed time sequence data into the network. It makes me confused. So I want to know how your cnn_lstm_block works exactly.
Hope for reply. Thanks.

**Comment by wangjksjtu** [comment]
Thanks for the interest in our work! Yes, you should disable the shuffling line when you use the DNN-LSTM structure. 

Note that we only release the code for DNN-only in this repo (see README.md). The cnn_lstm_block is just for reference. It is neither tested nor cleaned in this repo.

**Comment by jycccccccc** [comment]
Thanks a lot!
