### ISSUE TITLE
Cannot download dataset from site<ftp://user1:User1314@121.192.180.185>

### ISSUE THREAD

**Issue by kalcohol** [driving-behavior/DBNet#5]
Just as the title, i try ping to this host <121.192.180.185> and it always return timeout.
Another site is available now?

Many thanks.

**Comment by wangjksjtu** [comment]
Yes, you are right. It seems that there is something wrong in the server. We are working on it now. I will inform you as soon as it is fixed. Very sorry for the inconvenience.

**Comment by wangjksjtu** [comment]
Hi, previously, the traffic was banned by the network department - they found the abnormal traffic. Now they recovered the connection :) 

Can you download the data now? If so, you can close this issue.

**Comment by kalcohol** [comment]
dear @wangjksjtu , thanks for your great work, the data set could download now.
many thanks again. old drivers could drive and restrat now.

**Comment by qiangxu1996** [comment]
The FTP server seems to be down again. Any chance to bring it back or provide alternative links? Thanks in advance.
