### ISSUE TITLE
problem about your lstm block

### ISSUE THREAD

**Issue by milk-bottle-liyu** [driving-behavior/DBNet#6]
Hi, I read your code and found a problem about your lstm block. Usually we don't shuffle the input data of lstm, but in your provider model, you shuffle the file names in function provider.read_from().

Won't shuffle break the data sequence or I miss something?
Thank u~

**Comment by wangjksjtu** [comment]
Hi, @public1024. You are correct! When you run the lstm model, the data sequence has to be maintained. You need to comment this line like the provider (Provider2) for testing.
https://github.com/driving-behavior/DBNet/blob/53dd1b2d3d609257920bb3553ca3d012abe29f0e/provider.py#L103

Note that this demo code is only tested on the __nvidia-pn__ model. You are welcome to submit pull-requests for other settings :) Recently, I am busy in doing other things. I will provide full supports as well as the results if I get a chance.

**Comment by milk-bottle-liyu** [comment]
thanks! Wonderful job!
