### ISSUE TITLE
Since you had the pcd2las，why you still use the CC viewer？

### ISSUE THREAD

**Issue by yileichen123** [driving-behavior/DBNet#8]

**Comment by wangjksjtu** [comment]
Hi, *pcd2las.py* is a script which utilizes CloudCompare software to finish format conversion. To successfully use pcd2las, you have to install the CloudCompare and adjust the ***path*** in the script.

**Comment by yileichen123** [comment]
Is the operation under the  windows or linux as I see CloudCompare.exe in the order?

**Comment by wangjksjtu** [comment]
It can be done both in windows & Linux as long as you install the CloudCompare and configure the path. In windows, it is CloudCompare.exe.
