### ISSUE TITLE
The Prepared Data given doesn‘t have all the data

### ISSUE THREAD

**Issue by YihaoX** [driving-behavior/DBNet#9]
Hi, thanks for your wonderful research which teach me a lot but i cannot find the test dataset in the Prepared Data zip file. Could you provide us with them? thanks a lot.

**Comment by wangjksjtu** [comment]
Yes, we just uploaded the test data. You can download the prepared data again :)

**Comment by YihaoX** [comment]
> Yes, we just uploaded the test data. You can download the prepared data again :)

Got it! Thanks a lot my friend!

By the way, if there are any other ways to get the RAW data, like google drive or something? The connection to the RAW DATA source is unstable and slow actually and always failed....

Anyway, truly appreciate your reply & help.

**Comment by wangjksjtu** [comment]
Sorry for the unstable connection. The school restricts the flow... We are making efforts to provide faster download environments. Maybe we will move the data to Google Drive in the future.

**Comment by YihaoX** [comment]
> Sorry for the unstable connection. The school restricts the flow... We are making efforts to provide faster download environments. Maybe we will move the data to Google Drive in the future.

I see, thanks a lot!:D
